name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  update-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eqlabs/pathfinder
          tags: |
            type=semver,latest=true,pattern={{raw}}
            # pre-release builds don't update `latest` by default
            type=raw,value=latest,enable=${{ github.event_name == 'push' && startsWith('refs/tags/v', github.ref) }}
            type=raw,value=snapshot-{{branch}}-{{sha}},enable=false
      # Workaround for https://github.com/rust-lang/cargo/issues/8719
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
