name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  update-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eqlabs/pathfinder
          tags: |
            type=semver,latest=true,pattern={{raw}}
            # pre-release builds don't update `latest` by default
            type=raw,value=latest,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=snapshot-{{branch}}-{{sha}},enable=${{ github.event_name = 'workflow_dispatch' }}
